#!/bin/bash
# Wrapper so that 'goblin ...' is enough instead of 'java -jar ...'.
# Symlink to /usr/local/bin/goblin and adjust GOBLIN_JAR.
GOBLIN_JAR="${GOBLIN_JAR:-$(dirname "$(readlink -f "$0")")/goblin.jar}"
exec java -jar "$GOBLIN_JAR" "$@"
